on: 
  workflow_dispatch:
jobs:
  api_test:
    runs-on: ubuntu-latest
    steps:
      - name: protection
        run: |
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.demo1 }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Ayyappan-STC/test-repo/branches/main/protection -d '{"required_status_checks":{"strict":false,"contexts":[]},"enforce_admins":false,"required_pull_request_reviews":{"dismissal_restrictions":{},"dismiss_stale_reviews":false,"require_code_owner_reviews":false,"required_approving_review_count":1,"require_last_push_approval":false,"bypass_pull_request_allowances":{}},"restrictions":{"users":[],"teams":[]},"required_linear_history":false,"allow_force_pushes":false,"allow_deletions":false,"block_creations":false,"required_conversation_resolution":false,"lock_branch":false,"allow_fork_syncing":false}'
